theme: minima
title: Krithik Ashokkumar
author: krithikashokkumar
email: mailkrithash@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  - Part-Time High School/College Math Tutor at Kumon North America, Inc.
  - Head of Entrepreneurship Department of a Nonprofit (EYDB)
  - Published Short Story and Poetry Writer

# social links
twitter_username: N/A
github_username:  krithikashokkumar

show_excerpts: true # set to false to remove excerpts on the homepage
