theme: architect
title: Krithik Ashokkumar
author: krithikashokkumar
email: mailkrithash@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Student at East Brunswick High School
 
# social links
twitter_username: N/A
github_username:  krithikashokkumar

show_excerpts: true # set to false to remove excerpts on the homepage
